Incorrect usage of await with require in the same level.
Error message:

console.log(`__dirname: ${__dirname}`);
                          ^

ReferenceError: Cannot determine intended module format because both require() and top-level await are present. If the code is intended to be CommonJS, wrap await in an async function. If the code is intended to be an ES module, replace require() with import.
    at file://node-express-course-freecodecamp/01-node-tutorial/globals-example.js:20:27
    at ModuleJob.run (node:internal/modules/esm/module_job:371:25)
    at async onImport.tracePromise.__proto__ (node:internal/modules/esm/loader:669:26)
    at async asyncRunEntryPointWithESMLoader (node:internal/modules/run_main:101:5) {
  code: 'ERR_AMBIGUOUS_MODULE_SYNTAX'
}